# Auto-Generated by device/samsung/a40/setup.sh
$(call inherit-product, device/samsung/a40/full_a40.mk)
$(call inherit-product, vendor/ancient/config/common_full_phone.mk)
PRODUCT_NAME := ancient_a40

# AncientOS Officialy Stuff
ANCIENT_OFFICIAL := true
TARGET_USES_BLUR := true
ANCIENT_GAPPS := false

# Additional Props
TARGET_FACE_UNLOCK_SUPPORTED := true
TARGET_BOOT_ANIMATION_RES := 1080
TARGET_DISABLE_POSTRENDER_CLEANUP := true
