# Auto-Generated by device/samsung/a20e/setup.sh
$(call inherit-product, device/samsung/a20e/full_a20e.mk)
$(call inherit-product, vendor/ancient/config/common_full_phone.mk)
PRODUCT_NAME := ancient_a20e

# AncientOS Officialy Stuff
ANCIENT_OFFICIAL := true
TARGET_USES_BLUR := true
ANCIENT_GAPPS := false

# Additional Props
TARGET_FACE_UNLOCK_SUPPORTED := true
TARGET_BOOT_ANIMATION_RES := 720
